package io.lumine.mythic.lib.version.wrapper;

import io.lumine.mythic.lib.MythicLib;
import io.lumine.mythic.lib.UtilityMethods;
import io.lumine.mythic.lib.api.item.ItemTag;
import io.lumine.mythic.lib.api.item.NBTItem;
import io.lumine.mythic.lib.util.annotation.BackwardsCompatibility;
import io.lumine.mythic.lib.version.OreDrops;
import io.lumine.mythic.lib.version.VInventoryView;
import io.lumine.mythic.lib.version.api.GameProfile;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.Sound;
import org.bukkit.attribute.AttributeModifier;
import org.bukkit.block.Biome;
import org.bukkit.block.Block;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Entity;
import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.FurnaceRecipe;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.SkullMeta;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.UUID;

public interface VersionWrapper {

    static final String PLAYER_PROFILE_NAME = "SkullTexture";

    public static VersionWrapper get() {
        return MythicLib.plugin.getVersion().getWrapper();
    }

    /**
     * @return Either a GameProfile object or PlayerProfile depending on version.
     */
    GameProfile getProfile(SkullMeta meta);

    /**
     * This takes in either a GameProfile object or PlayerProfile object and applies it
     * to the target skull meta depending on server version.
     */
    void setProfile(SkullMeta meta, GameProfile profile);

    /**
     * Spigot 1.20 introduced an API method to manipulate skull textures
     * without having to rely on reflection. Previous versions still
     * rely on reflection while newer versions can switch to the API.
     * <p>
     * The new PlayerProfile API requires to both support PlayerProfile
     * and GameProfile objects as reflection is no longer supported by >1.20.2
     */
    GameProfile newProfile(UUID uniqueId, String textureValue);

    /**
     * Unique ID is injectively generated from the texture value.
     *
     * @see #newProfile(UUID, String)
     */
    default GameProfile newProfile(String textureValue) {
        return newProfile(UtilityMethods.uniqueIdFromString(textureValue), textureValue);
    }

    /**
     * Used by MMOItems to check if a block can be autosmelt. Also
     * used to apply Fortune levels for loot multiplication.
     *
     * @param material Type of broken block
     * @return Drops of provided block if it's an ore, null otherwise. The drops correspond
     *         to the autosmelt drops, not the vanilla block drops.
     */
    OreDrops getOreDrops(Material material);

    /**
     * Used by MMOItems when eating consumables the vanilla way. There is an
     * issue where when eating items, the saturation and food buff still applies
     * which MMOItems need to take an offset of.
     *
     * @param item Has to be a food item
     * @return Food restored when eating
     * @throws NullPointerException If it is not a food item
     */
    int getFoodRestored(ItemStack item);

    /**
     * This is necessary because Bukkit 1.14 don't have
     * such a method which was introduced in Bukkit 1.15
     *
     * @return Between 0 and 1, 1 being a fully charged attack
     */
    float getAttackCooldown(Player player);

    /**
     * Used by MMOCore to check if a block has been generated by a
     * cobblestone or obsidian generator.
     *
     * @param material Block material
     */
    boolean isGeneratorOutput(Material material);

    /**
     * Used by MMOItems when eating consumables the vanilla way. There is an
     * issue where when eating items, the saturation and food buff still applies
     * which MMOItems need to take an offset of.
     *
     * @param item Has to be a food item
     * @return Saturation restored when eating
     * @throws NullPointerException If it is not a food item
     */
    float getSaturationRestored(ItemStack item);

    FurnaceRecipe getFurnaceRecipe(String path, ItemStack item, Material material, float exp, int cook);

    @Deprecated
    default NBTItem copyTexture(NBTItem item) {
        return getNBTItem(new ItemStack(item.getItem().getType())).addTag(new ItemTag("CustomModelData", item.getInteger("CustomModelData")));
    }

    @Deprecated
    default ItemStack textureItem(Material material, int modelData) {
        final ItemStack stack = new ItemStack(material);
        final ItemMeta meta = stack.getItemMeta();
        meta.setCustomModelData(modelData);
        stack.setItemMeta(meta);
        return stack;
    }

    Enchantment getEnchantmentFromString(String s);

    FurnaceRecipe getFurnaceRecipe(NamespacedKey key, ItemStack item, Material material, float exp, int cook);

    boolean isCropFullyGrown(Block block);

    // Mostly NMS based methods from here
    NBTItem getNBTItem(ItemStack item);

    /**
     * {@link Material#getEquipmentSlot()} was only introduced in 1.17+
     *
     * @param material Material to check
     * @return If given material is, by default, a helmet
     */
    default EquipmentSlot getEquipmentSlot(Material material) {
        return material.getEquipmentSlot();
    }

    default void sendActionBar(Player player, String message) {
        sendActionBarRaw(player, "{\"text\": \"" + message + "\"}");
    }

    void sendActionBarRaw(Player player, String message);

    /**
     * Sends a raw chat message
     */
    void sendJson(Player player, String message);

    void playArmAnimation(Player player);

    Sound getBlockPlaceSound(Block block);

    String getSkullValue(Block block);

    void setSkullValue(Block block, String textureValue);

    default AttributeModifier newAttributeModifier(@NotNull NamespacedKey key, double amount, @NotNull AttributeModifier.Operation operation) {
        final String str = key.toString();
        return new AttributeModifier(UtilityMethods.uniqueIdFromString(str), str, amount, operation);
    }

    /**
     * Re-implementation of {@link LivingEntity#damage(double, Entity)} that returns a boolean
     * to indicate if the damage was successfully dealt.
     *
     * @param target Entity to damage
     * @param amount Amount of damage dealt
     * @param source Source of damage.
     * @return True if the damage was dealt successful, false otherwise
     */
    boolean damage(@NotNull LivingEntity target, double amount, @Nullable Entity source);

    /**
     * In 1.21.2+ Biome was changed from an Enum to an interface.
     */
    @BackwardsCompatibility(version = "1.21.2")
    default String getBiomeName(@NotNull Biome biome) {
        return biome.getKey().getKey().toUpperCase();
    }

    /**
     * In 1.21.2+ Sound was changed from an Enum to an interface.
     */
    @BackwardsCompatibility(version = "1.21.2")
    default String getSoundName(@NotNull Sound sound) {
        return sound.getKey().getKey().toUpperCase();
    }

    default boolean matches(AttributeModifier modifier, NamespacedKey key) {
        return modifier.getName().equals(key.toString());
    }

    VInventoryView getView(InventoryEvent event);

    VInventoryView getOpenInventory(@NotNull Player player);

    InventoryClickEvent newInventoryClickEvent(@NotNull VInventoryView view, @NotNull InventoryType.SlotType type, int slot, @NotNull ClickType click, @NotNull InventoryAction action);
}
